# Generated by Django 4.0.1 on 2022-01-31 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_body_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='owner',
        ),
    ]
